version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm cit
  
workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
